### SETAS

In [1]:
import pandas as pd

In [2]:
data_87 = pd.read_csv('..\\data\\1987_data.csv', sep=',')
data_class = pd.read_csv('..\\data\\primary_data_edited.csv', sep=';')

In [3]:
data_87.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   class                     8124 non-null   object
 1   cap-shape                 8124 non-null   object
 2   cap-surface               8124 non-null   object
 3   cap-color                 8124 non-null   object
 4   bruises                   8124 non-null   object
 5   odor                      8124 non-null   object
 6   gill-attachment           8124 non-null   object
 7   gill-spacing              8124 non-null   object
 8   gill-size                 8124 non-null   object
 9   gill-color                8124 non-null   object
 10  stalk-shape               8124 non-null   object
 11  stalk-root                8124 non-null   object
 12  stalk-surface-above-ring  8124 non-null   object
 13  stalk-surface-below-ring  8124 non-null   object
 14  stalk-color-above-ring    8124 non-null   object
 15  stalk-color-below-ring    8124 non-null   object
 16  veil-type                 8124 non-null   object
 17  veil-color                8124 non-null   object
 18  ring-number               8124 non-null   object
 19  ring-type                 8124 non-null   object
 20  spore-print-color         8124 non-null   object
 21  population                8124 non-null   object
 22  habitat                   8124 non-null   object
dtypes: object(23)
memory usage: 1.4+ MB

In [4]:
data_87.describe()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
count,8124,8124,8124,8124,8124,8124,8124,8124,8124,8124,...,8124,8124,8124,8124,8124,8124,8124,8124,8124,8124
unique,2,6,4,10,2,9,2,2,2,12,...,4,9,9,1,4,3,5,9,6,7
top,e,x,y,n,f,n,f,c,b,b,...,s,w,w,p,w,o,p,w,v,d
freq,4208,3656,3244,2284,4748,3528,7914,6812,5612,1728,...,4936,4464,4384,8124,7924,7488,3968,2388,4040,3148

In [8]:
data_87.nunique(axis=0).sum()

119

In [9]:
data_87['class'].value_counts(normalize=True)

class
e    0.517971
p    0.482029
Name: proportion, dtype: float64

In [8]:
data_87.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g

In [11]:
data_class.head()

,family,name,class,cap-diameter,cap-shape,cap-surface,cap-color,does-bruise-or-bleed,gill-attachment,gill-spacing,...,stem-root,stem-surface,stem-color,veil-type,veil-color,has-ring,ring-type,Spore-print-color,habitat,season
0,Amanita Family,Fly Agaric,p,"[10, 20]","[x, f]","[g, h]","[e, o]",[f],[e],NaN,...,[s],[y],[w],[u],[w],[t],"[g, p]",NaN,[d],"[u, a, w]"
1,Amanita Family,Panther Cap,p,"[5, 10]","[p, x]",[g],[n],[f],[e],NaN,...,NaN,[y],[w],[u],[w],[t],[p],NaN,[d],"[u, a]"
2,Amanita Family,False Panther Cap,p,"[10, 15]","[x, f]",NaN,"[g, n]",[f],[e],NaN,...,NaN,NaN,[w],[u],[w],[t],"[e, g]",NaN,[d],"[u, a]"
3,Amanita Family,The Blusher,e,"[5, 15]","[x, f]",NaN,[n],[t],NaN,NaN,...,[b],NaN,[w],[u],[w],[t],[g],NaN,[d],"[u, a]"
4,Amanita Family,Death Cap,p,"[5, 12]","[x, f]",[h],[r],[f],NaN,[c],...,NaN,NaN,[w],[u],[w],[t],"[g, p]",NaN,[d],"[u, a]"

In [15]:
data_class['class'].value_counts(normalize=True)

class
p    0.554913
e    0.445087
Name: proportion, dtype: float64

In [10]:
data_class.describe()

,family,name,class,cap-diameter,cap-shape,cap-surface,cap-color,does-bruise-or-bleed,gill-attachment,gill-spacing,...,stem-root,stem-surface,stem-color,veil-type,veil-color,has-ring,ring-type,Spore-print-color,habitat,season
count,173,173,173,173,173,133,173,173,145,102,...,27,65,173,9,21,173,166,18,173,173
unique,23,173,2,51,27,40,67,2,8,3,...,5,14,41,1,7,2,13,8,21,10
top,Tricholoma Family,Fly Agaric,p,"[2, 5]",[x],[y],[n],[f],[a],[c],...,[s],[s],[w],[u],[w],[f],[f],[k],[d],"[u, a]"
freq,43,1,96,16,48,14,38,143,32,70,...,9,15,57,9,15,130,137,5,104,106

In [11]:
data_class.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 173 entries, 0 to 172
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   family                173 non-null    object
 1   name                  173 non-null    object
 2   class                 173 non-null    object
 3   cap-diameter          173 non-null    object
 4   cap-shape             173 non-null    object
 5   cap-surface           133 non-null    object
 6   cap-color             173 non-null    object
 7   does-bruise-or-bleed  173 non-null    object
 8   gill-attachment       145 non-null    object
 9   gill-spacing          102 non-null    object
 10  gill-color            173 non-null    object
 11  stem-height           173 non-null    object
 12  stem-width            173 non-null    object
 13  stem-root             27 non-null     object
 14  stem-surface          65 non-null     object
 15  stem-color            173 non-null    object
 16  veil-type             9 non-null      object
 17  veil-color            21 non-null     object
 18  has-ring              173 non-null    object
 19  ring-type             166 non-null    object
 20  Spore-print-color     18 non-null     object
 21  habitat               173 non-null    object
 22  season                173 non-null    object
dtypes: object(23)
memory usage: 31.2+ KB

In [12]:
images = pd.read_csv('..\\data\\images\\_classes.csv')

In [13]:
images.head()

,filename,Amanita Vaginata Var - Vaginata,Amanita brunneitoxicaria,Amanita phalloides-,Amanita princeps Corner - Bas,Chlorophyllum molybdites,Lactarius glaucescens,Lentinus polychrous Berk,Lentinus squarrosulas Mont,Macrolepiota gracilenta,Mycoamaranthus cambodgensis,Pleurotus pulmonarius,Schizophylllum commune,Scleroderma sinnamariense
0,IMG_20230131_10221_Burst10_jpg.rf.3d0d859972a6...,0,0,0,0,0,0,1,0,0,0,0,0,0
1,IMG_20230131_105942_Burst18_jpg.rf.3cd9527b1bb...,0,0,0,0,0,0,0,0,0,1,0,0,0
2,IMG_20230205_210944_Burst11_jpg.rf.3d4a5083517...,0,1,0,0,0,0,0,0,0,0,0,0,0
3,IMG_20230206_114826_Burst18_jpg.rf.3cf73ef01b0...,0,0,0,0,0,1,0,0,0,0,0,0,0
4,IMG_20230207_120343_Burst20_jpg.rf.3cdd35e4008...,0,0,0,0,0,0,0,0,0,1,0,0,0

In [24]:
images.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6693 entries, 0 to 6692
Data columns (total 14 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   filename                          6693 non-null   object
 1    Amanita Vaginata Var - Vaginata  6693 non-null   int64
 2    Amanita brunneitoxicaria         6693 non-null   int64
 3    Amanita phalloides-              6693 non-null   int64
 4    Amanita princeps Corner - Bas    6693 non-null   int64
 5    Chlorophyllum molybdites         6693 non-null   int64
 6    Lactarius glaucescens            6693 non-null   int64
 7    Lentinus polychrous Berk         6693 non-null   int64
 8    Lentinus squarrosulas Mont       6693 non-null   int64
 9    Macrolepiota gracilenta          6693 non-null   int64
 10   Mycoamaranthus cambodgensis      6693 non-null   int64
 11   Pleurotus pulmonarius            6693 non-null   int64
 12   Schizophylllum commune           6693 non-null   int64
 13   Scleroderma sinnamariense        6693 non-null   int64
dtypes: int64(13), object(1)
memory usage: 732.2+ KB

In [23]:
images.sum(numeric_only=True)

 Amanita Vaginata Var - Vaginata      28
 Amanita brunneitoxicaria            500
 Amanita phalloides-                 654
 Amanita princeps Corner - Bas       564
 Chlorophyllum molybdites            679
 Lactarius glaucescens               655
 Lentinus polychrous Berk            356
 Lentinus squarrosulas Mont          129
 Macrolepiota gracilenta             555
 Mycoamaranthus cambodgensis         659
 Pleurotus pulmonarius               120
 Schizophylllum commune             1099
 Scleroderma sinnamariense           695
dtype: int64